### ISSUE TITLE
Handle twitch.tv links etc.

### ISSUE THREAD

**Issue by FoseFx** [bttv-android/bttv#10]
Right now only the official Twitch App is opened. :/

**Comment by FoseFx** [comment]
Seems like the intent-filters are set up correctly. I identified autoVerify as a possible issue.

**Comment by FoseFx** [comment]
Twitch set up an Android App Link Handler for `tv.twitch.android.app`. This, by design, will open the official Twitch app every time one of the twitch domains is used in Chrome for example. Only the user can change this behavior by going to `Settings -> Apps -> Twitch -> Standard for -> To supported Links -> Select "Always Ask"`.

**Comment by kinsi55** [comment]
I'm encountering this issue myself, your mentioned Setting does not exist for me (Android 12) so I did the next best thing, disabled handling of all URLs by the official app and enabled them for bttv - this still results in all links being opened by the official app, and if I uninstall the official app, they will just be opened in the browser
