### ISSUE TITLE
FrankerFaceZ/BTTV Highlighted Terms feature

### ISSUE THREAD

**Issue by LEMIBANDDEXARI** [bttv-android/bttv#104]
Add the functionality available on FrankerFaceZ and BTTV to be able to highlight the terms you want in the chat.

**Comment by FoseFx** [comment]
@all-contributors add @LEMIBANDDEXARI for ideas

**Comment by FoseFx** [comment]
@all-contributors please add @LEMIBANDDEXARI for ideas
