### ISSUE TITLE
Updater doesn't download update

### ISSUE THREAD

**Issue by RootPC** [bttv-android/bttv#135]
Manually updated to 0.7.1.
Got notification today that an update to 0.8.0 is available
Opened updater
Progress bar doesn't load, nothing happens. No prompt to allow access
Went in settings - special access - install unknown apps, enabled BTTV. Still nothing.

Android 11, LG v60

**Comment by FoseFx** [comment]
Something makes the request to the apk file fail.
Do you have anything set up that could interfere with it? Like some kind of firewall and antivirus or sth. to save bandwidth?

**Comment by Rouids** [comment]
Negative. I disabled the built in Security app and uninstalled CCleaner. I did notice the app only requests Media access, not File access. Not sure if that would affect anything. ![Screenshot_20210618-105311.png](https://user-images.githubusercontent.com/18724313/122588649-f3a4dc80-d024-11eb-8583-06fc2486fb31.png)

**Comment by SnugglyFruit** [comment]
Same issue. I tried force closing the app, giving all permissions and updating but still, it won't work. I updated to the v0.8.0-beta manually tho.

**Comment by FoseFx** [comment]
I just (https://github.com/bttv-android/bttv/commit/c185e15fd83637d011fe0cfa79d8cc980221db89) added a Dialog that shows when an error has occurred  while downloading. This will ship in 0.8.1-beta. Let's hope this will help tracking down the problem.

**Comment by Rouids** [comment]
As an update, at one point today while on mobile data, the app did start downloading the file (progress bar started filling up), I switched to WiFi, and it stopped. Closed the app, turned wifi off, and tried again on mobile data, and it didn't do anything again. Nothing else had changed.

**Comment by ascott18** [comment]
I encountered this one, then a few days later tried the update again and it worked fine. I didn't do anything special in the intervening time.

**Comment by FoseFx** [comment]
As v0.8.2-beta was just released you should now see a popup with an error message when the download fails. Can you share this information?

**Comment by RootPC** [comment]
![Screenshots_2021-07-01-07-09-48.png](https://user-images.githubusercontent.com/18724313/124115197-1d9dcc00-da33-11eb-88e7-31f0b5f99d12.png)

**Comment by FoseFx** [comment]
Whatever stops you from connecting to the Github assets server, it is not bttv-android, so there is little I can do. Unfortunately I have to close this unresolved :/

**Comment by ascott18** [comment]
@FoseFx It looks like from the error message that the connection timeout is only 60ms? This is unreasonably short for even the best of connections and network conditions.

**Comment by FoseFx** [comment]
You might have a point there! I'll have a look at it tomorrow.

**Comment by FoseFx** [comment]
Let's see if 9ad417117c581ca1d6701edf45779693b169095e will fix it

**Comment by artemis-a09** [comment]
So i still have this problem in 0.8.1 for updating to the newest version. Tried literally everything even vpn but still can't get the update.
N bc I'm pepega i don't know how to update manually. 
![Screenshot_20210704-062515](https://user-images.githubusercontent.com/86899775/124370922-9bf7a980-dc91-11eb-8a85-237e5a04c1ea.png)

**Comment by FoseFx** [comment]
You can just download it from the latest release https://github.com/bttv-android/bttv/releases/latest and install it. All your local data will remain.

**Comment by SnugglyFruit** [comment]
The problem remained until 0.9.1. .However, when 0.9.2 was released, the app updated to 09.2 without any problems! If people confirm such behavior, then you may have fixed this! No matter the outcome though, good job!
