### ISSUE TITLE
Error on translation of redeemed channel points

### ISSUE THREAD

**Issue by Santagain** [bttv-android/bttv#138]
- Bug

![photo_2021-06-17_20-10-27](https://user-images.githubusercontent.com/15141090/122483168-5b691200-cfa8-11eb-9ec1-308492d0c6ab.jpg)

the same error occurred on Header Modal where it was supposed to be "JonDoe is giving X inscriptions as a gift" when a person gave subs as gifts, but I couldn't make a screenshot in time.

**Comment by FoseFx** [comment]
This seems to be related to go's xml parser trying to be smarter than it should be (or me not being aware of it, you choose).
I'm just waiting for somebody to waste their points for a highlighted message to confirm it is fixed.

@all-contributors please add @Santagain for bug
