### ISSUE TITLE
Make update notifications less frequent

### ISSUE THREAD

**Issue by Spkz** [bttv-android/bttv#139]
Having an application maintaining itself outside of an app store, and having a project being maintained is unironically really cool, and I really do appreciate it.

But....Could we recieve the update push notifications less frequently please? I was not able to turn them off or do a 'remind me later', and the app was reminding me that there's an update every 30 minutes or so until the point I eventually downloaded and installed the update.

Android 10, Samsung Galaxy S8

**Comment by FoseFx** [comment]
What version are you on? There was a bug that was [fixed](https://github.com/bttv-android/bttv/commit/653ccfef5d8f9f3d254cc644c5a7f30201941aaa) in v.0.7.1-beta that caused the background service to run as often as possible.

**Comment by Spkz** [comment]
Yes, it was from 0.7.1 beta to 0.8 I believe, so if it is already fixed then thank you!

**Comment by FoseFx** [comment]
If it was 0.7.1-beta it should not have happened. Let me downgrade my installation and do some testing.

**Comment by FoseFx** [comment]
@all-contributors please add @Spkz for bug
