### ISSUE TITLE
version 0.8.0 not updating to 0.8.1

### ISSUE THREAD

**Issue by 0genGH** [bttv-android/bttv#162]
i got the notification to install it and left it for about 10 minutes and the progress bar would not move and then finally resorted to manually installing it and it went fine (i dont have a firewall/antivirus or anything that could interrupt it from installing and have the unknown apps allowed and permissions for storage, but nothing).

**Comment by FoseFx** [comment]
Closing as this issue is already tracked by #135. Please share new information that could aid in fixing this there.
