### ISSUE TITLE
Plurals are incorrectly escaped

### ISSUE THREAD

**Issue by Santagain** [bttv-android/bttv#167]
## Bug Report

**Current Behavior**
Error on Parse Message on hypetrain and pools

**Expected behavior/code**
Strings parse correctly

**Environment**

- bttv-android version:  v0.8.1-beta
- Android version: Pie, 9
- Device: Moto G6 Plus

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/15141090/123886255-6f583080-d925-11eb-8f9a-98b3428c04d8.png)
![image](https://user-images.githubusercontent.com/15141090/123886274-78e19880-d925-11eb-80e1-a44deb627bc0.png)

**Comment by FoseFx** [comment]
I think this stems from a bug in apktool, I opened an appropriate issue: https://github.com/iBotPeaches/Apktool/issues/2601
There is an easy workaround though!
