### ISSUE TITLE
Crash when opening DMs

### ISSUE THREAD

**Issue by peaceboi** [bttv-android/bttv#168]
## Bug Report

**Current Behavior**
Opening DMs crashed the app after loading for ~3sec.

**Expected behavior/code**
Notmal access to DMs

**Environment**

- bttv-android version: [e.g. v0.8.0-beta]
- Android version: OneUI 3.1 /Android 11
- Device: S21 Ultra

Screencap attached.

https://user-images.githubusercontent.com/86738069/124003940-ca4a6000-d9d7-11eb-8865-9f8feb55ba9a.mp4

**Comment by FoseFx** [comment]
Dupe of #166 Thanks for the report anyway!
