### ISSUE TITLE
Highlight Keywords in VODs

### ISSUE THREAD

**Issue by ashamefuldog** [bttv-android/bttv#179]
Honestly not sure if this is a bug or a feature request, I'll assume feature request and ask if it'd be possible to get chat keyword highlights working on VODs, seems like they only work on livestreams unless I goofed something up. 

Also, I'd love to have the extension's ability to add specific usernames to the list of keywords using parenthesis in order to always highlight messages from those users.

**Comment by FoseFx** [comment]
Hey! I split this into two issues so they are easier to track for me. Thank you for your input!

@all-contributors please add @ashamefuldog for ideas
