### ISSUE TITLE
webp anim 7TV Emotes aren't animated

### ISSUE THREAD

**Issue by StephanBruh** [bttv-android/bttv#183]
## Bug Report

**Current Behavior**
Emotes on 7TV that should be animated are just static

**Expected behavior/code**
7TV Emotes are animated

**Environment**

- bttv-android version: v0.8.2
- Android version: 10
- Device: OnePlus 6T

**Comment by FoseFx** [comment]
Can't confirm. Are there certain emotes that don't work for you?

**Comment by StephanBruh** [comment]
> Can't confirm. Are there certain emotes that don't work for you?

Oh yeah, looks like its only happening to certian wide animated emotes, some example;
https://7tv.app/emotes/60ae6b4486fc40d488d0b324
https://7tv.app/emotes/60b1868058275001781a8bd5
https://7tv.app/emotes/60b2cd2aab2a2a9c958b2695
https://7tv.app/emotes/60ae47919986a00349442244

But some do work for me like;
https://7tv.app/emotes/6043a11f1d4963000d9dae4c
https://7tv.app/emotes/6063d9f8f4dc10001426b946

**Comment by FoseFx** [comment]
The reason is probably, that e.g. AlienGathering has the mime type `image/webp` not `image/gif` and bttv-android/Glide can not determine whether it should be animated.

**Comment by FoseFx** [comment]
This is a known issue in Glide, litte I can do about it https://github.com/bumptech/glide/issues/571 :/

**Comment by StephanBruh** [comment]
Damn thats a old issue, maybe your able to count the frames and change the mime?

**Comment by FoseFx** [comment]
I'll have a look at https://github.com/zjupure/GlideWebpDecoder and see if I can add it somehow

**Comment by StephanBruh** [comment]
Reopening issue because emotes with webp are still not animated.

emote example;
https://7tv.app/emotes/60b529e7c871a89f1541972e
https://7tv.app/emotes/60845b712a652395a02c56ef

**Comment by FoseFx** [comment]
I'm working on the v11.4.0 rebase right now and there it seems to work. Idk what fixed it but I'll take it.
So this will be fixed in v0.11.0-beta.

**Comment by StephanBruh** [comment]
Alright thanks! Yeah I know they are static in the emote picker. Will wait for the beta then :)
