### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by Mizinov** [bttv-android/bttv#188]
## Bug Report

**Current Behavior**
lags alot

**Expected behavior/code**
I have been watching big streamer and of course the chat is so fast maybe that's the reason why it's lagging. If there's a fix it's definitely gonna be good. At first stream is not lagging at all but after few minutes of watching it starts lagging and lagging.

**Environment**

- bttv-android version: latest
- Android version: 10
- Device: vivo

**Additional context/Screenshots**
can't screenshot a lag :)

**Comment by FoseFx** [comment]
Already discussed here: #152
