### ISSUE TITLE
Messages from blocked users are always displayed on the phone

### ISSUE THREAD

**Issue by LEMIBANDDEXARI** [bttv-android/bttv#189]
## Bug Report

**Current Behavior**
Messages from blocked users are always displayed on the phone when watching a replay.

**Expected behavior/code**
On twitch on a pc, we no longer see messages from blocked users at all and even in replay.

**Environment**

- bttv-android version: v0.8.2-beta
- Android version: On different versions of android

**Additional context/Screenshots**
Bug reported by xplod62

**Comment by FoseFx** [comment]
How does the normal Twitch app behave?

**Comment by LEMIBANDDEXARI** [comment]
On the official twitch application we also see messages from blocked people.

**Comment by FoseFx** [comment]
Then that has to be classified as intended behavior.

**Comment by LEMIBANDDEXARI** [comment]
Okay, so it's clear for this concern if someone brings up this topic again. ☺️
