### ISSUE TITLE
Stream uptime

### ISSUE THREAD

**Issue by Epicnicity322** [bttv-android/bttv#192]
## Feature Request

Show a timer of how long the stream has been going for, I've seen other mods place this timer on top of "Live" and it's really useful if you are friends of some streamers

![IMG_20210705_175510](https://user-images.githubusercontent.com/13574419/124517399-3eab4780-ddba-11eb-92e3-b0d34b0b2b66.jpg)

**Comment by FoseFx** [comment]
Closed due to new [Scope of the project](https://github.com/bttv-android/bttv/blob/master/CONTRIBUTING.md#scope-of-the-project)
