### ISSUE TITLE
Changing the width of the chat in landscape mode

### ISSUE THREAD

**Issue by LEMIBANDDEXARI** [bttv-android/bttv#193]
## Feature Request

**Is your feature request related to a problem? Please describe.**

We would like to be able to change the width of the chat to landscape mode as is possible on the "Xtra for Twitch" app.

**Describe the solution you'd like**

You should be able to choose the width of the chat as a percentage, as shown in the image 
![image](https://user-images.githubusercontent.com/70129787/124878295-3a567880-dfcc-11eb-8ec2-a4330d03dc37.png)
This is a screenshot taken from the Xtra for Twitch app to illustrate what we would like as a new feature.

The idea for adding this feature came from @xplod62

**Comment by FoseFx** [comment]
Closed due to new [Scope of the project](https://github.com/bttv-android/bttv/blob/master/CONTRIBUTING.md#scope-of-the-project)
