### ISSUE TITLE
Player behind the notch

### ISSUE THREAD

**Issue by StephanBruh** [bttv-android/bttv#202]
## Feature Request

**Is your feature request related to a problem? Please describe.**
No.

Would be great if the player could go behind/under the notch on a phone. Blank space right know what could be perfectly filled.

**Describe the solution you'd like**

Fill this blank space (Screenshot taken on a OnePlus 6T)
![image](https://user-images.githubusercontent.com/19285400/126009872-f6d79bcf-0ba3-45bf-b794-a458e417d398.png)

**Comment by FoseFx** [comment]
I think this is out of scope for this project.
