### ISSUE TITLE
Emotes don't update when switching streams

### ISSUE THREAD

**Issue by Epicnicity322** [bttv-android/bttv#206]
## Bug Report

When you first open the app, join a stream, then switch to another streamer, the emotes that have the same name are the same from first streamer. Look how in this picture, the KEKW emote doesn't match the chat in the streamer's screen.
![IMG_20210723_193628](https://user-images.githubusercontent.com/13574419/126847898-96132a39-a8b2-48d0-bd07-fab6a6f172d0.jpg)
This seem to happen with only emotes that have the same name but different icons.

**Environment**

- bttv-android version: v0.8.2
- Android version: 10
- Device: Redmi Note 8 Pro

**Comment by icynstant** [comment]
Got this problem again with new 7TV API
