### ISSUE TITLE
Add BTTV emote suggestions

### ISSUE THREAD

**Issue by colahobi** [bttv-android/bttv#209]
## Feature Request

**Describe the solution you'd like**

The twitch app comes with emote suggestions when you type the ":" symbol. Unfortunately, when I do this, only default twitch emote suggestions pop up, and not BTTV emotes. 

I liked this feature when I was using the app Xtra, and although I prefer this app more overall, I miss that feature.

**Comment by FoseFx** [comment]
@all-contributors please add @colahobi for ideas
