### ISSUE TITLE
Bttv/ffz/7tv emotes aren't shown in subscription message

### ISSUE THREAD

**Issue by Epicnicity322** [bttv-android/bttv#216]
## Bug Report

**Current Behavior**
When typing the codename of an emote it is not shown in the subscription message.

**Expected behavior/code**
Bttv emotes pictures to be shown in subscription message, since twitch emotes are shown.

**Environment**

- bttv-android version: [e.g. v0.9.2-beta]
- Android version: 10
- Device: Redmi Note 8 Pro

**Additional context/Screenshots**
![IMG_20210801_171240](https://user-images.githubusercontent.com/13574419/127784225-6b538264-d127-4d64-8c29-97e264adcf90.jpg)

**Comment by FoseFx** [comment]
Yeah, I think we [only add them in "normal" text tokens](https://github.com/bttv-android/bttv/blob/master/mod/app/src/main/java/bttv/Tokenizer.java#L79), so I assume it wont work in highlighted messages (using channel points) either.

**Comment by FoseFx** [comment]
@all-contributors please add @Epicnicity322 for bugs
