### ISSUE TITLE
Unable to subscribe from the app

### ISSUE THREAD

**Issue by LEMIBANDDEXARI** [bttv-android/bttv#226]
## Bug Report

**Current Behavior**
You cannot subscribe to a twitch channel. There is only the option to use the Prime membership.
And you can't offer a subscription to another person either.

**Expected behavior/code**
On the Twitch app we can take out a subscription and even offer one in addition to using Prime.

**Environment**

- bttv-android version: v0.9.2-beta
We are 3 people on the bttv discord to have noticed the same thing.

**Comment by FoseFx** [comment]
You are probably correct, I had no time to look into this yet, but if this is true it should be at least communicated to the user and fail with a proper message.

**Comment by GauravM512** [comment]
> You are probably correct, I had no time to look into this yet, but if this is true it should be at least communicated to the user and fail with a proper message.

Either you can redirect them to web page where they can subscribe the creator?

**Comment by FoseFx** [comment]
That's a great idea! Thank you.
