### ISSUE TITLE
Add option to disable floating chat.

### ISSUE THREAD

**Issue by FlippedSuit** [bttv-android/bttv#243]
I would like to have the option to revert the fullscreen landscape chat back to pushing over the stream image like it used to.

**Comment by FoseFx** [comment]
Thank you for your interest in the project! I have troubles understanding the issue. bttv-android does not add a floating chat feature. Can you provide a screenshot so I can understand you better?

**Comment by FlippedSuit** [comment]
![Screenshot_20210901-164941](https://user-images.githubusercontent.com/85626580/131749966-f1f0c69f-e7b0-4133-80cb-901a195a60c5.png)
This does not appear on the current twitch app

**Comment by FoseFx** [comment]
Pinch your fingers together on the stream. Like you would want to zoom out of it. This is normal Twitch behavior.

**Comment by FlippedSuit** [comment]
Sorry for wasting your time, haven't done this in a while.

**Comment by Cingolani23** [comment]
Still not working for me
