### ISSUE TITLE
Change emote picker grid size

### ISSUE THREAD

**Issue by hurokast** [bttv-android/bttv#244]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I don't know if this is possible, but it would be useful if we were able to change the grid size of the emote picker. 

**Describe the solution you'd like**
Right now, the grid size (you can see at once) is 5x4. I would see an option in the settings to change the width and height individually (probably between 5x4 and 7x6), or have presets to choose from (again between 5x4 and 7x6).

**Comment by FoseFx** [comment]
Closed due to new [Scope of the project](https://github.com/bttv-android/bttv/blob/master/CONTRIBUTING.md#scope-of-the-project)
