### ISSUE TITLE
Spaces are removed when copying messages with emotes

### ISSUE THREAD

**Issue by nelswad90** [bttv-android/bttv#257]
## Bug Report

**Current Behavior**
Copying messages with emotes removes the spaces and fails to paste properly.

**Expected behavior/code**
Example "JammiesPOGGERSPOGSLIDE" should have been copied as "Jammies POGGERS POGSLIDE"

**Environment**

- bttv-android version: 0.12.0-beta
- Android version: 11
- Device: Samsung Galaxy S10

**Comment by FoseFx** [comment]
I compared "PogChamp PogChamp" in both twitch and bttv-android. The spaces between Emotes are missing everywhere. I'll fix this.

**Comment by FoseFx** [comment]
@all-contributors please add @nelswad90 for bugs
