### ISSUE TITLE
Bug with Emotes

### ISSUE THREAD

**Issue by idiot1788** [bttv-android/bttv#264]
I just checked if my sub emote is already approved and noticed this bug. https://youtube.com/shorts/OMhuq923kUA?feature=share

**Comment by FoseFx** [comment]
I think this is an issue with the overall architecture of the mod. It assumes you can only be in once chat at the same time. Unfortunately I doubt I can fix this anytime soon :/.

**Comment by shinelucid** [comment]
> hi its me again xd not opening a new thread because this is another emote bug looks kinda funny tho https://youtube.com/shorts/6Sjv186gfK4?feature=share (edited because i linked a more detailed video)

UP
