### ISSUE TITLE
Bttv emotes are no longer visible

### ISSUE THREAD

**Issue by Senpai206** [bttv-android/bttv#269]
Since the new twitch update (adding animated sub emotes to android) i can no longer see the bttv, ffz and even 7tv emotes. I can only see global twitch emotes and the new animated sub emotes.

**Comment by Senpai206** [comment]
Btw here's how it looks like for me (empty spaces instead of text or emote) 
![Screenshot_20210924_081352_tv twitch bttvandroid app](https://user-images.githubusercontent.com/68463773/134633693-c493ec3b-fb2e-4f23-817b-43532c6467bf.jpg)

**Comment by Senpai206** [comment]
Update : it seems like it works fine if im watching a VOD but the problem only happens when im watching live

**Comment by FoseFx** [comment]
Can you confirm this is fixed in [v0.13.1-beta](https://github.com/bttv-android/bttv/releases/tag/v0.13.1-beta)?

**Comment by Senpai206** [comment]
Yeah after updating the app (v0.13.1-beta), my problem is fixed. Thank you so much.
