### ISSUE TITLE
Consolidate rendering for animted emotes (native/BTTV)

### ISSUE THREAD

**Issue by ReggX** [bttv-android/bttv#274]
## Feature Request

Hey there.

Now that Twitch has integrated animated emote rendering natively in the their app (play animation for a few seconds then freeze), how about reusing the same rendering pipeline for animated BTTV emotes.

Larger chats with lots of emote spam tend to lag out weaker Android processors, so freezing animations could help lead to an improvement in quality of life.

In contrast, an option to not freeze native animated emotes could be interesting for people with high power Android devices.

Therefore, I propose exploring ways to consolidate animated emote rendering for both native and BTTV emotes and add an additional option that lets users choose if they want unlimited animation / stop animation after some time / static images only.

**Comment by FoseFx** [comment]
I am [aware](https://github.com/bttv-android/bttv/issues/152#issuecomment-869163132) of the performance issues when a lot of emotes are used, but never figured out why. The mod is generating "normal" Emote Objects, though I had to do some trickery to get the animations to work in the first place. I'll have a look at what has changed and how (or if) a better integration is possible.

**Comment by FoseFx** [comment]
Let's hope this will also fix #152. Thank you for bringing this up again! This will land in 0.14.0-beta once I can rebase to the new twitch version.

**Comment by FoseFx** [comment]
[v0.14.0-beta](https://github.com/bttv-android/bttv/releases/tag/v0.14.0-beta) was just released!
