### ISSUE TITLE
Split Chat Improvement

### ISSUE THREAD

**Issue by LEMIBANDDEXARI** [bttv-android/bttv#287]
## Feature Request

We would like to be able to customize the design of the Split Chat

**Describe the solution you'd like**

For example with Frankerfacez on Twitch on pc, we can choose different Spli Chat design :

![1](https://user-images.githubusercontent.com/70129787/136084932-d409be53-2d6c-42d2-b827-97c6864b2f4c.png)
And here's what it looks like on the chat 
![2](https://user-images.githubusercontent.com/70129787/136085076-e54a5c5c-3000-4f61-8432-fd7e464ff27d.png)

2nd choice possible
![3](https://user-images.githubusercontent.com/70129787/136085214-f815806a-e6d3-40c2-875f-01e8f7b1b696.png)
![4](https://user-images.githubusercontent.com/70129787/136085221-e49b45aa-c79f-4c33-abb1-d771cbf0ebdb.png)

3rd choice possible
![5](https://user-images.githubusercontent.com/70129787/136085354-e482efdb-d8d7-46a9-8500-736e1c13c373.png)
![6](https://user-images.githubusercontent.com/70129787/136085360-a0f1881b-0ab8-42db-bee6-dd392df4f5be.png)

4th choice possible
![7](https://user-images.githubusercontent.com/70129787/136085706-616d37c3-9bf6-438d-9d42-77b005657af4.png)
![8](https://user-images.githubusercontent.com/70129787/136085716-c9a11579-ca8a-4186-94f4-3253496c2119.png)

5th choice possible
![9](https://user-images.githubusercontent.com/70129787/136085825-52fb4285-ea9f-4ec7-9600-8619eaa8f639.png)
![10](https://user-images.githubusercontent.com/70129787/136085829-ff89c060-175f-4645-91cf-ebea9277594d.png)

We should see what works best on the phone, for example also the bttv split chat?
![bttv](https://user-images.githubusercontent.com/70129787/136088473-74e669f2-26da-4ecb-a0f9-ce7b5e296469.png)

We find that the colors of the current Split chat on the app are too light, 
Can we darken them and make the colors more match the colors of Frankerfacez's Split chat?

**Comment by FoseFx** [comment]
> We find that the colors of the current Split chat on the app are too light,
Can we darken them and make the colors more match the colors of Frankerfacez's Split chat?

[Done](https://github.com/bttv-android/bttv/commit/2bfe50be80753653b84dc3a08bc8f6d88279e840)

> We would like to be able to customize the design of the Split Chat

I have decided against this. I understand that customizing things is awesome, but it comes at great costs: clutter, degraded stability and ultimately degraded maintainability. For me these factors are more important.
