### ISSUE TITLE
Chat stops updating randomly in vods

### ISSUE THREAD

**Issue by MrAl3x1s** [bttv-android/bttv#335]
## Bug Report

**Current Behavior**
Chat messages in a vod stop coming in randomly and don't resume until the vod is closed and re-opened, even as the video continues normally, and chat messages were being sent at the time.

**Environment**

- bttv-android version: 0.16.0
- Android version: 11
- Device: samsung s10

**Comment by FoseFx** [comment]
Duplicate of #327
