### ISSUE TITLE
Simple swipe down on stream to lower it (like back functionality)

### ISSUE THREAD

**Issue by akalineskou** [bttv-android/bttv#339]
Firstly, I would like to thank you for the effort you've put in this app.

## Feature Request

**Is your feature request related to a problem? Please describe.**

It's not a problem per se, but right now I have to show the back button (swipe up at the bottom) and then tap the back button to show the list of followed streams.
Click on a stream, then until I find something to view, I have to show the buttons again and tap back, rinse and repeat.

**Describe the solution you'd like**

A simple swipe down on the stream would handle it like doing a back button, lower the stream in the corner.
Hopefully I've explained it correctly... I've used a custom twitch app (xtra if you know it, but it's been since removed from the app store, and found this one) and it had that functionality and it was super useful to quickly change stream.

**Comment by FoseFx** [comment]
I think this is a native feature by now. Either way, it's out of scope for this project, sorry!
