### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by jhurag** [bttv-android/bttv#340]
Would it be possible to have this app for Android TV with correct responsivness to remote and stuff?

Right now it's very awkward to handle with remote because mainly you dont visually see at what option you are.

**Comment by FoseFx** [comment]
I am confused, did you install bttv-android on an Android TV? I'm not sure, but IIRC there is a separate Twitch App for TVs, which is not the App bttv-android is based on.

**Comment by jhurag** [comment]
Yea i installed bttv-android on Android TV. Ah i thought it's same app just different layout. I assume it would be hard to do bttv for TV app as well?

**Comment by FoseFx** [comment]
I just confirmed that they are indeed two completely different Apps.
Right now there are no plans to maintain an Android TV version of bttv-android, but I will keep this issue open in case that changes in the future.

**Comment by FoseFx** [comment]
Closing, there are still no plans to implement this, nor do I think there will ever be.
