### ISSUE TITLE
Some twitch emotes and added emotes are in "negative colors"

### ISSUE THREAD

**Issue by Thobo35000** [bttv-android/bttv#342]
**Current Behavior**
Some twitch emotes like Kappa , bttv and others added emotes like KEKW ,even some channel emotes for sub(doesn't seem to do it everytime like the twitch or bttv ones though, I can't seem to redo it on purpose sorry) , when send in tchat look like they are in negative colors 

**Expected behavior/code**
The expected thing would be "normal" colors in tchat , because when you are on the "emote keyboard" the colors are the normal ones .

**Environment**

- bttv-android version: bttv v0.17.0(but it was already there in 0.16.0 )
- Android version: MIUI Global 12.5.2
- Device:Mi 9T pro

**Additional context/Screenshots**
https://youtu.be/iAWAc1Lubgw (sorry for the low quality video I hope it's good enough for you to see the bug)

Ps: Sorry for any typos and I hope what I wrote is understandable 😅

**Comment by FoseFx** [comment]
I could unfortunately not reproduce this, not on my phone and not in the emulator, not in the chat of the streamer in the video and not in others.

Does this happen to you reliably or just sometimes?
Does this happen in the official twitch app as well?
Did you update your system recently? If so, did it happen before that as well?

**Comment by Thobo35000** [comment]
Yup for kappa and kekw it's all the time as well for example as LebronJam with the same frame doing it all the time , for the sub emotes it seems like it doesn't happen a lot at all though
It only happens with the bttv app and not in the official app.
And no I don't think I updated my system recently ,I only updated the bttv app recently but it happened before the bttv's update.

**Comment by Thobo35000** [comment]
Hiiii , I think I found a new thing , it seems to only happen when I'm in the dark mode on twitch .Cause when I'm in default mode every emotes work just fine so maybe it can help

**Comment by Thobo35000** [comment]
Maybe it actually is only when it's not my twitch app in dark mode but my phone and my screen in night mode if it makes sens

**Comment by Thobo35000** [comment]
Sorry for a third message in such a little amount of time but it seems like activate the dark mode on both twitch and my screen(I only did activate my phone's one before) make all work fine . I'm a little dumb ahah ,I hope it can still help someone eheh😊

**Comment by FoseFx** [comment]
There seems to be [an issue with "Dark Mode 2.0" in MIUI 12.5][1]. If I understood you correctly this is the feature you were using before, right? Does everything work when using Twitch's Dark Mode?

[1]: https://piunikaweb.com/2021/08/05/miui-12-5-users-complain-of-dark-mode-issues-with-apps-like-messenger-snapchat/

**Comment by Thobo35000** [comment]
Yup when I have dark mode from MIUI 12.5 on , the app seems to be in darkmode like all in black and purple, so I forgot to put the dark mode from the app which led to those bugs with emotes, but when I activate both dark modes all work fine now. So yes the dark mode from MIUI 12.5 does weird thing to emotes if you forget to also activate the twitch dark mode

**Comment by Thobo35000** [comment]
You don't have to turn off the dark mode from miui in the app by app settings(if ti makes sense) for the app to run just fine. You juts need to activate both dark mode and all is fine eheh 
Ps:sorry to have posted a bit too much answers ahah
