### ISSUE TITLE
App is draining battery quickly

### ISSUE THREAD

**Issue by AoiKC** [bttv-android/bttv#361]
Hi, Bringing this to your attention been using the lastest apk on the Samsung Galaxy Fold 3 usually watching streams with alot of bttv in chat and battery has been draining almost twice as fast as the Main Twitch app but the phone doesn't get hot or laggy while in use. Here's a screenshot of the battery usage. [
![Screenshot_20220100-152057_Device care](https://user-images.githubusercontent.com/96956387/147859845-599b043d-3f20-4c02-8ad8-cad1a5767322.jpg)
](url)

_Originally posted by @AoiKC in https://github.com/bttv-android/bttv/issues/152#issuecomment-1003615878_

**Comment by FoseFx** [comment]
Please see this comment: https://github.com/bttv-android/bttv/issues/152#issuecomment-869163132

If you are experiencing issues it is advised to disable GIF Emotes, they seem to be the problem.
