### ISSUE TITLE
The 7tv emotes of the channel are not appearing

### ISSUE THREAD

**Issue by hotroro7575** [bttv-android/bttv#381]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Expected behavior/code**

**Environment**

- bttv-android version: [e.g. v0.8.0-beta]
- Android version: [e.g. Oreo, 11, ...]
- Device:

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by FoseFx** [comment]
Yes, they do, I just verified that. As no proper bug report was issued I can not really give any help here.
