### ISSUE TITLE
Proper Fullscreen

### ISSUE THREAD

**Issue by MohsenEssa** [bttv-android/bttv#391]
Can you please try to ignore notches/cutouts phone screens are too small already. opening chat and watching could be way much better if the app didn't waste so much of my display for nothing.

**Comment by FoseFx** [comment]
Unfortunately this is not in the [Scope of the Project](https://github.com/bttv-android/bttv/blob/master/CONTRIBUTING.md#scope-of-the-project). Feel free to [open a support ticket with Twitch](https://help.twitch.tv/s/contactsupport) though.

**Comment by MohsenEssa** [comment]
Thank you. I submitted my request there :)
