### ISSUE TITLE
Getting ads on recent update

### ISSUE THREAD

**Issue by Balasia** [bttv-android/bttv#396]
Title. After recent update getting ads during vods and sometimes emotes will just break.

**Comment by FoseFx** [comment]
bttv-android [does not block ads](https://github.com/bttv-android/bttv/issues/87#issuecomment-855405919).

The "emotes will just break" part is much more concerning to me. Can you open a new bug report issue with some more details? What does "break" mean? Which emotes break, can you provide an example? Where do they break (Live, VoD, Emote Picker)?
