### ISSUE TITLE
Emotes appear too small and some appear blurry

### ISSUE THREAD

**Issue by mariusandersen** [bttv-android/bttv#411]
## Bug Report

**Current Behavior**
Custom emotes appear too small. Especially "wide" emotes.

**Expected behavior/code**
When you use custom emotes from BTTV FFZ or 7TV the size should be bigger than the text in height. Wide emotes (for instance "widepeepoHappy") appear so small they are barely understandable.

Comparing the emote quality to PC browsers, the quality of some of the emotes also look blurry/lowres. Might be less noticable on phones, but on a Tablet it's very noticable.

**Environment**

- bttv-android version: latest
- Android version: 12
- Device: Xiaomi Pad 5 (Tablet)

**Additional context/Screenshots**
If you need it and it's not clear I can provide it, but pretty obvious when using the app.

**Comment by FoseFx** [comment]
I found indicators that wide emotes still work in VODs and this only happens in Live Chat. Can someone confirm this? I did not find a VOD with wide emotes in it that quickly, so if someone has a link to share that would be great!

**Comment by mariusandersen** [comment]
Wide emotes are fine in VODs

https://i.imgur.com/O4anpJ0.jpg

**Comment by mariusandersen** [comment]
I appreciate you for fixing this item but I just tested it and it seems bugged. 

The emote cuts off (in default size). Only after I click the emote, it will show fully. See [video](https://www.youtube.com/watch?v=n-MJVyqOEAc)
