### ISSUE TITLE
Re-fetch Set of Emotes on 7TV `channel-emotes` update events

### ISSUE THREAD

**Issue by FoseFx** [bttv-android/bttv#415]
## Feature Request

This came up on Discord and I want to formalize things here.

Apparently 7TV has an [HTTP SSE][sse] API that one can [listen on for a set of given channels][stvapi] that emits an `update` event when a channel's emote list was updated. bttv-android could listen to that and fetch all emotes again when such an event is emitted.

[sse]: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events
[stvapi]: https://github.com/SevenTV/EventAPI#seventv-eventapi

**Comment by FoseFx** [comment]
The problem I have with this is mainly in the cost/value calculation of this. 

**Cost**:
A server sent events request requires a tcp socket to the 7TV servers to be open for the duration of the whole stream which means lots of burnt CPU cycles. This is not a real problem on PC but might be one on mobile devices which run on battery.

bttv-android consumes enough CPU for rendering animated emotes as it is and I don't want to worsen the experience for people on low-end devices.

The other problem I have is with privacy: We essentially tell the server that a certain user (i.e. IP address) is watching what channel for how long.

So this definitely has to be an opt-in feature.

Plus this is yet another feature to maintain.

**Value**

People don't have to restart the app anymore when a streamer adds a new 7TV (!) emote. Right now the Emote Set is cached in memory for the duration of one use for all channels.

How often does that happen? In my experience streamers usually look for new Emotes off-stream.
How many people will this benefit? Arguably not too many. 7TV does not have wide spread adoption yet.

I don't think this is worth having a connection open with 99.99% heartbeat events as nothing has changed.

**Alternative**:

Manual refresh. When the streamer adds new Emotes they probably tell the viewers, which can then manually initiate a reload. This would be perfect to add to the stream settings or stream-chat settings.

I'm happy to hear y 'all's opinions on this.

**Comment by LEMIBANDDEXARI** [comment]
It's a feature that would affect very few people and that brings more annoyance than real utility from my point of view.
It's a feature that would affect very few people and that brings more annoyance than real usefulness from my point of view.
A manual refresh is fast and the streamers who add emotes live and in particular on 7TV to my knowledge I do not know of any and yet I use 7TV too.
Here is my opinion
