### ISSUE TITLE
Rotating screen while downloading update will reset progress bar

### ISSUE THREAD

**Issue by TheDearbear** [bttv-android/bttv#440]
## Bug Report

**Current Behavior**
If you rotate screen (e.g. Portrait->Landscape) while BTTV downloading updated apk, it will reset progress bar.
**Expected behavior/code**
Rotated screen with saved progress bar status.

**Environment**

- bttv-android version: 0.25.0-beta
- Android version: 12 (by PixelExperience)
- Device: Xiaomi Mi 8

**Comment by FoseFx** [comment]
@all-contributors please add @TheDearbear for bug

**Comment by FoseFx** [comment]
Thank you for reporting this!
