### ISSUE TITLE
Live emote suggestion

### ISSUE THREAD

**Issue by JackTrueax** [bttv-android/bttv#454]
## Feature Request

**Is your feature request related to a problem? Please describe.**

This is a recommended additional feature to the chat input.
When a channel has many emotes, it can be tedious to find the emote I want when I do not know its proper capitalization or name to type it.

**Describe the solution you'd like**

I recommend adding a popup above the text input field in a chat. This popup would display a list of emotes (and/or usernames) in the channel based on the word the cursor is currently on in the message. The user can tap on one of these emotes and it will be added to your message.

Here's an example from a separate open source twitch chat app (DankChat https://f-droid.org/packages/com.flxrs.dankchat )
![Screenshot_20220423-145204_DankChat](https://user-images.githubusercontent.com/25124158/164943258-59ef4350-d0fb-4d31-bf09-7882384f69d7.jpg)
![Screenshot_20220423-151826_DankChat](https://user-images.githubusercontent.com/25124158/164943260-7dee3582-9b01-43a8-b310-ccaaa30c4a99.jpg)

I attached one image in dark mode and one in light mode to show that it would be a popup above the chat input field.

This is not a search box for the emotes, although it can fulfill that purpose. This is a live emote suggester that checks each word as you type.

I am not sure how much this would impact performace, but surely it can be optimized. Also, this would require a newly designed ui element, which may need extra consideration. 
Overall though, it should be feasible to implement because the app already has access to all emotes in the channel, which includes their name and icon. All that would be required is a search through the emotes after parsing the current word and comparing the emote names to the word.

**Comment by FoseFx** [comment]
You can use a colon (":") to autocomplete emotes. This is a native Twitch feature and bttv-android emotes are integrated there as well!

e.g. ":wide"

**Comment by JackTrueax** [comment]
incredible. Thank you!
