### ISSUE TITLE
Stream delay since past 2 updates

### ISSUE THREAD

**Issue by Doomski99** [bttv-android/bttv#458]
## Bug Report

**Current Behavior**
Long delay between stream and chat, compared to official twitch app and pc, from the moment I start a stream. 
Pausing and resuming stream doesn't resync as it used to do in older versions. This behavior still applies in the official twitch app (just checked). 

**Expected behavior/code**
Low delay like in pc and twitch official app. 
Pausing and resuming to resync the stream instead of resuming from last paused frame. 

**Environment**

- bttv-android version: v0.26.0-beta
- Android version: 12
- Device: Poco X3 Pro

**Additional context/Screenshots*
If I was unclear please do let me know. 
Thank you for your amazing work :)

**Comment by FoseFx** [comment]
Can't reproduce :/

https://drive.google.com/file/d/1vfIMaQf09he_-2CSqS41HyDUlmokbZJZ/view?usp=sharing (sry for autofocus)

**Comment by Doomski99** [comment]
> Can't reproduce :/
> 
> https://drive.google.com/file/d/1vfIMaQf09he_-2CSqS41HyDUlmokbZJZ/view?usp=sharing (sry for autofocus)

Couldn't open the file, private. Nonetheless,  thank you! I've assumed that it's working for you, so I uninstalled the app completely (should've done that before, sorry) and re-installed it. Now it's working as intended :D
