### ISSUE TITLE
Switching streams while Casting 

### ISSUE THREAD

**Issue by wacra** [bttv-android/bttv#464]
BTTV 0.27.0-beta
Twitch v13.0.0

While casting if you switch channels the stream on the TV doesn't change.

On the phone it switches and shows the player page of the new stream but for the stream to switch on TV you have to switch resolutions for it to refresh.

**Comment by FoseFx** [comment]
Hey! Can you check if this happens with the unmodded Twitch App (v13.0.0+) as well?

**Comment by wacra** [comment]
> Hey! Can you check if this happens with the unmodded Twitch App (v13.0.0+) as well?

I checked, it does.
My bad should have checked right away, only use your app for over a year now.
