### ISSUE TITLE
bottom shop are not displaying can't chat

### ISSUE THREAD

**Issue by freshkurt42** [bttv-android/bttv#477]
love this! thank you! 

guess I should have said this first I'm running a Samsung 10 plus running Android 12 with the Samsung UI 4.0.1 latest update that just came out yesterday, but this issue actually started happening in version 0.28 so I don't know it might be an issue with twitches back end, might want to look into that.
thanks again I love all of you! 💙💯

**Comment by FoseFx** [comment]
OP fixed this by re-installing (#482)
