### ISSUE TITLE
Be able to copy messages

### ISSUE THREAD

**Issue by zezofelipe** [bttv-android/bttv#487]
![2022_06_28_20 13 29](https://user-images.githubusercontent.com/37094298/176320874-c4b5bc1d-ef99-4c1b-bd30-9c69a9616797.jpg)

It may not be directly linked to bttv, but it will greatly improve the experience in the app, especially with the Moderation stuff. I will be grateful to have this feature in future updates.

**Comment by FoseFx** [comment]
You can long press to copy a message already!

**Comment by zezofelipe** [comment]
> You can long press to copy a message already!

Doesn't work when you are a Moderator, or on its own channel.

**Comment by FoseFx** [comment]
![Screenshot_2022-06-30-10-52-09-44_34750238b5877b2a91c912748cb283f8.jpg](https://user-images.githubusercontent.com/22842759/176635642-fb60895d-6234-4f11-9218-658f7c574e50.jpg)

![Screenshot_2022-06-30-10-51-05-74_34750238b5877b2a91c912748cb283f8__01.jpg](https://user-images.githubusercontent.com/22842759/176635706-243c047f-63dc-48f0-b966-eba7f682f24e.jpg)

Both seem to work fine for me
