### ISSUE TITLE
Condense header when casting

### ISSUE THREAD

**Issue by deviant14** [bttv-android/bttv#490]
I noticed this in particular when I tried to split screen on Android as well. There's no way to see the chat. But it seems it takes up more space than necessary all the time while casting.

![Capture+_2022-06-29-16-53-27](https://user-images.githubusercontent.com/76411063/176543470-94a179c3-3486-4785-914e-8fe2a92a7a2b.png)

That said, thanks for making casting work as well as it does.

**Comment by FoseFx** [comment]
I don't think this is [in scope of the project](https://github.com/bttv-android/bttv/blob/master/CONTRIBUTING.md#scope-of-the-project). Also it would be _a lot_ of work for a very niche feature. Thank you for your interest in the project though!
