### ISSUE TITLE
Push notifications 

### ISSUE THREAD

**Issue by CrazyWolf13** [bttv-android/bttv#492]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

I don't get push notifications but i turned them on in the app.

### bttv-android version

Latest updated today

### android version

9.0

### device

A8 2018

**Comment by FoseFx** [comment]
Someone on the discord fixed this by giving "the app default app thing". Which I assume they mean this from the installation documentation:
> 3. (Optional) Prevent Twitch from opening when you interact with twitch.tv links: Long-press on the Twitch App -> "App Info" -> "Advanced" -> "Open by default" -> "Open supported links" -> "Ask every time" (might vary depending on OEM)

LMK if this helps!

**Comment by CrazyWolf13** [comment]
Thanks, i now disabled this, if this is what you meant. I'll try.
The strange thing is, this worked all the time and after a factory reset and new installationit stopped working, but i never had to change anything in the settings.

I let you know if it worked. Thanks
Have a nice day

**Comment by CrazyWolf13** [comment]
So i did this and now it seems to work, great!
App-Info --> Open Supported Apps--> only in this application.
With this setting it works now.

Thanks for the help.
