### ISSUE TITLE
Blacklist does not block out message

### ISSUE THREAD

**Issue by mklwong** [bttv-android/bttv#506]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

I added a the word vagina to the blacklist. It gets added to the blacklist dialog box but doesn't remove chat messages with the word.

I tried to add capitalisation and plural and it still doesn't work.

Thanks for your response.

### bttv-android version

0.30.1-beta

### android version

12

### device

Pixel 3

**Comment by FoseFx** [comment]
Hey! Thank you for your interest in the project! Sorry for the late response I am a little bit low on time right now.

Messages that have already arrived are not removed, but new messages that contain words on the blacklist are not shown.
Is this the behavior you see or do new messages with the offending word still arrive?

**Comment by mklwong** [comment]
Thanks, just wanted to say up front I love this project, so thanks for you hard work!

Messages with the offending word still arrives.

On a slightly related question, do you know how this interact with the twitch apps default text filter? I've tried with the following combinations:
- both on: message arrives with offending word replaced with ******
- Twitch on BTTV off: message arrives with offending word replaced with ******
- Twitch off, BTTV on: message arrives unfiltered

**Comment by FoseFx** [comment]
@all-contributors please add @mklwong for bug
