### ISSUE TITLE
app not installed android 6

### ISSUE THREAD

**Issue by shinelucid** [bttv-android/bttv#517]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

as in the title the app doesn't install, this is the first time I get this issue in the bttv-android since like version 0.23 or so, regular Twitch app installs perfectly fine, I also get error when updating through the app.

### bttv-android version

0.31

### android version

6

### device

Samsung Galaxy J7

**Comment by FoseFx** [comment]
I just tried it out on an emulator with android 6 installed and I could install and update it without a problem.
I just had problems logging in, so I could not use it (also with the unmodded app).

Do you have enough space left on the device?
Do you see any errors?

Can you try to uninstall and install the new version by hand?

**Comment by shinelucid** [comment]
The app installs successfully after uninstalling previous version, It couldn't update from previous version like it usually does but now it worker after I uninstalled and reinstalled the new version.
