### ISSUE TITLE
can't blacklist words in caps 

### ISSUE THREAD

**Issue by owwouwu** [bttv-android/bttv#523]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

words which are blacklisted will appear in chat if they are in caps, but we also can't blacklist words in caps.

**Comment by FoseFx** [comment]
@all-contributors please add @owwouwu for bug
