### ISSUE TITLE
Problem downloading the app file 

### ISSUE THREAD

**Issue by OkayegTeaTim3** [bttv-android/bttv#541]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

In the middle of downloading the file it keeps saying: couldn't download files, any fixes?

### bttv-android version

v0.32.1

### android version

12

### device

Samsung s21

**Comment by FoseFx** [comment]
Do you have enough space left on your device? Is the internet connection stable? Other than that I have no Ideas :/
