### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by Ivanajusup** [bttv-android/bttv#544]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

When someone posts a link in chat it doesnt work, it just shows up as text rather than an actual link. 

### bttv-android version

O.32.1-beta

### android version

11

### device

Samsung galaxy a50

**Comment by FoseFx** [comment]
Duplicate of #531
