### ISSUE TITLE
Bring back is the sleeping timer ⏰

### ISSUE THREAD

**Issue by HamzaKov** [bttv-android/bttv#546]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

Hello Hello !!
Since bttv v0.31.0-beta, we lost the sleeping timer button in the live, but not in the Vods.
Can you bring back the button in the live streams like bttv v0.30.1-beta ?
Thanking you in advance ✌️

### bttv-android version

v0.33.0-beta

### android version

12

### device

Poco F4 GT

**Comment by FoseFx** [comment]
I tried to reproduce it with an Android 12 Emulator with the same screen sizes as the Poco F4 GT has according to GSMArea. I can see the sleeping timer button on live streams just fine.
Did you disable it in the settings?

**Comment by HamzaKov** [comment]
I I reproduced it on my phone, I filmed everything please find bellow the [video]() [video](https://we.tl/t-nW2vGYuxCU) .

https://we.tl/t-nW2vGYuxCU

**Comment by pbutin** [comment]
I have the same issue.
I have the button on the videos but not on the lives.

bttv-android version
v0.33.0-beta

android version
11

device
OnePlus 7 Pro

**Comment by AlexWayfer** [comment]
I see this button on version 0.33.0-beta, OnePlus 9R, so I believe we can close this issue.

The button looks like a moon.

![image](https://user-images.githubusercontent.com/6510020/198880178-2f5c654a-37aa-49be-8091-a63181785d68.png)

![image](https://user-images.githubusercontent.com/6510020/198880187-9a39c37e-9507-407b-91c5-6a685f7ec7a8.png)

**Comment by FoseFx** [comment]
Something makes the app use a different layout.
My hunch is that is has something to do with the screen size (it's not uncommon that different screen sizes get different layouts), but I have not found any indicator for this (there used to be though, so maybe it has moved somewhere where I have not found it yet).
It is also possible that twitch is running an experiment that changes the layout (I have also not found anything related to this yet though) and that's why only some of you do not see the icon.
This needs some more investigating.

**Comment by pbutin** [comment]
I just come back to tell that the issue is fixed on my app. The moon button is back.

As @FoseFx sayed, it might be twitch running same A/B testing. I have seen some color changes on the stream layout (like black empty space became greyish on the side on the stream).

**Comment by HamzaKov** [comment]
Ooh yes !!!
Thank you it's working now 👌
![Screenshot_2022-11-07-11-37-24-192_tv twitch bttvandroid app](https://user-images.githubusercontent.com/116479472/200290215-a296965e-81ca-427d-ac03-9181d0913e61.jpg)
![Screenshot_2022-11-07-11-37-33-697_tv twitch bttvandroid app](https://user-images.githubusercontent.com/116479472/200290229-a6198198-85e2-42c2-a0e9-42bfcace5b0a.jpg)
![Screenshot_2022-11-07-11-37-37-451_tv twitch bttvandroid app](https://user-images.githubusercontent.com/116479472/200290236-0299b997-641f-4456-ba38-90d97d4e5173.jpg)

**Comment by HamzaKov** [comment]
The moon button is back on BTTV 0.33.0-beta !
i close this issue
