### ISSUE TITLE
problem on devices with notch

### ISSUE THREAD

**Issue by GXFOS** [bttv-android/bttv#560]
In horizontal mode, a black bar is shown in the part of the notch, the same is done by activating the option to show notch with the default option of any android
![Screenshot_2022-12-06-14-24-01-172_tv twitch bttvandroid app](https://user-images.githubusercontent.com/79778144/205992462-39680af4-3dd9-46c2-aeb8-7661e44be8a5.jpg)

**Comment by FoseFx** [comment]
Does this happen in the unmodded twitch app as well?

**Comment by bepposax** [comment]
If it's still open I'd like to confirm this issue on MIUI. It happens with the twitch app too even after setting full screen mode and forcing the "always show notch" option.

**Comment by FoseFx** [comment]
Twitch-native issue. Can't/Won't fix
