### ISSUE TITLE
The stream is launched twice when an ad appears 

### ISSUE THREAD

**Issue by Omar2547** [bttv-android/bttv#561]
![Screenshot_2022-12-13-11-48-14-302_tv twitch bttvandroid app](https://user-images.githubusercontent.com/66215003/207298736-5393b37b-08ef-4505-9221-42848102d8d3.jpg)

**Comment by FoseFx** [comment]
Does this always happen? Was this in a squad stream or a normal stream? Does this happen in the unmodded twitch app as well?

**Comment by Omar2547** [comment]
Yes it happens always, in a normal stream, and I don't know if this happens in the unmodded twitch app

**Comment by FoseFx** [comment]
I'll close it as it is not clear if this is a twitch bug or a bttv-android bug and efforts to reproduce are not really viable. Feel free to re-open when you think this is a mistake.
