### ISSUE TITLE
Pop up window

### ISSUE THREAD

**Issue by Ivanajusup** [bttv-android/bttv#562]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [ ] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

The pop up window seems broken, when you try to move it across the screen it goes back to the bottom of the screen and closes itself. 

### bttv-android version

0.34.0-beta

### android version

11

### device

Samsung galaxy a50

**Comment by FoseFx** [comment]
Which pop up?

**Comment by Ivanajusup** [comment]
The pop out window, when youre watching a stream and you press the home
button to maybe go to a different app and the little pop out window you
have so you can still see the stream while in a different app.

uto, 20. pro 2022. 21:34 Max Baumann ***@***.***> je napisao:

**Comment by AlexWayfer** [comment]
It calls "picture-in-picture" or "PiP". The shell (Android's UI) breaks it oftenly than the app itself.

**Comment by FoseFx** [comment]
Ah, now I understand!
Yes pip is extremely buggy. When the issue occurs when you move the pip player it is very likely not an issue with bttv-android or twitch, but with the Android UI / samsung's UI and probably also occurs with other pip apps (youtube or chrome for example).

**Comment by AlexWayfer** [comment]
> Ah, now I understand! Yes pip is extremely buggy. When the issue occurs when you move the pip player it is very likely not an issue with bttv-android or twitch, but with the Android UI / samsung's UI and probably also occurs with other pip apps (youtube or chrome for example).

I can confirm that it's laggy for me with YouTube more often than with Twitch on Oxygen OS 12 and 13.
