### ISSUE TITLE
Sleep Timer disappeared

### ISSUE THREAD

**Issue by Dlevda** [bttv-android/bttv#571]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

in the latest version, the Sleep Timer icon disappeared

### bttv-android version

v0.35.0-beta

### android version

13

### device

Pixel 6

**Comment by MatteoCorsi33** [comment]
I noticed that the sleep timer work correctly with vods, the only place that is missing is during livestreams
