### ISSUE TITLE
Frozen 7tv emotes in zoomed view

### ISSUE THREAD

**Issue by Jayhanium** [bttv-android/bttv#596]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

Usually when you click on an emote thats been sent in the chat (animated or otherwise), it shows you a closeup of the emote and its name. For bttv (and twitch sub) animated emotes, it animates just fine. However when you tap on certain animated 7tv emotes, the closeup is completely frozen still, showing the first frame of the animation. For some reason a very very small set of 7tv emotes actually work fine. This bug existed for as long as I remember having this app (about 1-2 years).

### bttv-android version

0.36.0-beta

### android version

10

### device

Samsung Galaxy A20

**Comment by FoseFx** [comment]
This is already tracked in #199. I spend what feels like a lifetime debugging this and still don't really know why it behaves like this.

**Comment by Jayhanium** [comment]
ok so apparently this is also a problem in the emote list area (the tray that shows up when you click the smiley face next to the chatbox). just as before, a very very small subset of 7tv emotes are animated here too (the rest being frozen at the first frame) and all the bttv animated emotes work as normal.
