### ISSUE TITLE
"View info" on chatters goes to subscribe page for streamer instead of profile page for user

### ISSUE THREAD

**Issue by abraxas86** [bttv-android/bttv#597]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

_What's Happening:_  
When you long-tap a username in chat, then tap "View Info" from the menu, it opens a browser session and takes you to the subscribe page for the streamer whose chat you were in when you tried to view info.

_Expected Outcome:_  
Bttv takes you to the profile page for the user whose info you were trying to view.

### bttv-android version

0.36.0-beta

### android version

12

### device

Samsung Note10+ (SM-975W)

### Anything else?

Only started happening since the app updated.

**Comment by SwooshyCueb** [comment]
Having the same problem with Redmi K30 Pro/Poco F2 Pro running LineageOS 19.1

**Comment by FoseFx** [comment]
Thank you, everybody! It's fixed in the next release!

**Comment by abraxas86** [comment]
Confirmed, working perfectly now.  Thanks!
