### ISSUE TITLE
7tv emotes not available for selection when typing chat message

### ISSUE THREAD

**Issue by FAT9L** [bttv-android/bttv#598]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

When attempting to auto-complete emotes in a chat message using Twitch's native method (typing a '`:`', followed by a partial name), 7tv emotes sometimes do not appear. Comparison screenshots are attached. 

This is fixed with 1-2 relaunches of the app, achieved by force stopping and then reopening it. 

It seems that the emotes do not load approximately 50% of the time, which makes for easy testing at least. 

Obviously this is not a feature in the unmodded Twitch app, however it does not occur when using the browser version of 7tv. 

### bttv-android version

0.36.0-beta

### android version

13

### device

Samsung Galaxy S22 Ultra (SM-S908U1)

### Anything else?

Bugged behavior:

![Screenshot showing bug behavior](https://user-images.githubusercontent.com/96025485/226200089-1b162098-5f2e-44d9-b5de-8073f60037b4.png)

Correct behavior:

![Screenshot showing correct behavior](https://user-images.githubusercontent.com/96025485/226200124-0e4c3e17-da20-4e11-9f44-44b6bfe781fb.png)

**Comment by FoseFx** [comment]
Thank you for the report, but I tried it multiple times on multiple devices now and was not able to replicate it.
This maybe means Twitch is running an experiment that causes this breakage and we should keep an eye on it.

If you or somebody else is able to reliably replicate this please let me know.
