### ISSUE TITLE
Streams not loading as of May 18th

### ISSUE THREAD

**Issue by OnePunkArmy** [bttv-android/bttv#615]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

Starting May 18th, every stream does not load, and ends with "Network error, tap to retry." Chat works fine, but it's just videos and streams that do not load. The stock Twitch app works fine though. I have heard from another user that the app worked fine when mine didn't, so this could be isolated to specific devices.

### bttv-android version

v0.39.0-beta

### android version

13

### device

Pixel 4a 5G

**Comment by FoseFx** [comment]
I thought about this for the last 15 minutes, and I have no Idea what could cause this. My best guess is that you were put into some experiment that does not work that well. (You can check this by enabling the developer menu in the bttv settings and open the experiments screen. If something is not "reality!!" it may be the cause). You can reset your experiments in the experiments screen, or simply re-install the bttv-android. Let me know if this changed anything.

**Comment by OnePunkArmy** [comment]
Oh weird, I reinstalled yesterday but that didn't change anything. I reinstalled just now, and now the app works.

**Comment by GolfingSuccess** [comment]
I just faced this issue too; I feel like it shouldn't be closed. Yes, it only happened with the BTTV app and yes, after uninstalling and reinstalling it was fixed (temporarily?); simply reinstalling without uninstalling did nothing. And no, I wasn't in any experiment either.
