### ISSUE TITLE
Streams won't load

### ISSUE THREAD

**Issue by Vikings09876** [bttv-android/bttv#617]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

I can load previews of streams, and see chat, however the stream itself will never load. They just forever buffer till "Network error" is shown.

I've gone and downgraded my twitch app to 15.0.0, uninstalled and reinstalled the bttv app, restarted multiple times. Closed all apps, and reloaded and still no streams will load on the bttv app, but will on the normal twitch app.

### bttv-android version

0.39.0-Beta

### android version

12

### device

Samsung Galaxy S10

**Comment by Vikings09876** [comment]
I just reverted back to .38.0-beta and that version seems to be working just fine.

**Comment by kazie** [comment]
I've been having the same problem (for weeks)  on android 13 and tried everything in #615 trying to check experiments and reinstalling but nothing work.

Yo downgrade i had to do a clean install (uninstall + install) and now I am also on `.38.0-beta` and that works.

And the normal twitch app has always been working, and is currently at `15.3.1`. And yes I do understand that the regulars apps installation and version is irrelevant to the functionality of bttv. But maybe Twitch has made something on their side that specifically makes `.39-beta @ 15.0.0` incompatible?

**Comment by froz3n** [comment]
> I've been having the same problem (for weeks) on android 13 and tried everything in #615 trying to check experiments and reinstalling but nothing work.
> 
> Yo downgrade i had to do a clean install (uninstall + install) and now I am also on `.38.0-beta` and that works.
> 
> And the normal twitch app has always been working, and is currently at `15.3.1`. And yes I do understand that the regulars apps installation and version is irrelevant to the functionality of bttv. But maybe Twitch has made something on their side that specifically makes `.39-beta @ 15.0.0` incompatible?

I had network error when I tried playing a stream but the chat was fine. I read the linked problem and reinstalled, and it fixed the problem. I'm confused, what is actually causing the problem ?

**Comment by GorillaxJax** [comment]
I am having the exact same issue. Upgraded to .39.0-beta and am having the Network Error message, but chat, emotes, and the preview photos are working. Current version of Twitch works fine, downgrading to .39.0-beta fixes the issue, reinstalling .39.0-beta does not. Tried to see if any experiments were on but none were.

**Comment by Gnomercey** [comment]
I've got the same issue as of yesterday. Samsung S23 Ultra, Android 13. BTTV 0.39.0 Beta. Going to try a downgrade

**Comment by moo1012** [comment]
> 

I've started dealing with the same thing, was watching twitch and it randomly stopped working, chat is fine, but it won't load streams. And it works fine on the normal twitch app. Reveted back to .38.0 and that's working fine but still was weird for it to randomly stop working when it was working fine on that version for me for like 2 weeks

**Comment by kinshaft** [comment]
I have same issue too on my OnePlus 7 Pro, i downgraded 0.39 to 0.38 and it working fine

**Comment by BinToss** [comment]
Had this issue. Force-terminating the app in system setting then clearing the app's cache and data cleared up the issue without downwarding.
Everyone in the Experiments menu was set to `Reality!!`

**Comment by GorillaxJax** [comment]
Can confirm that works! Should have tried that the first time haha. Thanks for the work around!

Upgraded from .38 to .39, went to app info, force close, clear cache, clear data, log in again to BTTV app and it all works again.

**Comment by FoseFx** [comment]
Does this persist with v0.40.1-beta, released yesterday?

**Comment by Vikings09876** [comment]
> Does this persist with v0.40.1-beta, released yesterday?

I'm updating to it right now, will let you know.

**Comment by Vikings09876** [comment]
Currently it's working fine with updating to the newest version

**Comment by FoseFx** [comment]
Been a few days now. Did this happen to anyone yet on v0.40.1?

**Comment by mangkoran** [comment]
> Been a few days now. Did this happen to anyone yet on v0.40.1?

@FoseFx I have been using 0.40.1 since the update was released and no issue so far :D

**Comment by ubergeek77** [comment]
I haven't had this issue, but every now and then (rarely) the playback will turn black while audio still plays. It comes back a few seconds later. I block ads with a hosts file blocker, so maybe that's related. But otherwise it's working fine!

**Comment by FoseFx** [comment]
Closing as resolved then! Thank you everybody!

@all-contributors please add @Vikings09876 for Bug
