### ISSUE TITLE
Transparent background chat

### ISSUE THREAD

**Issue by MrSniFo** [bttv-android/bttv#621]
## Feature Request
When i rotate my screen the chat hides 30% of the screen, it's a little transparent but can you add an option so you can play with it.

**Comment by MrSniFo** [comment]
> Is #243 what you are looking for?

No, I mean that I can make chat like chat overlay an option to make the background more transparent, so i can see what behind it

**Comment by Zerwin** [comment]
I think this was natively implemented by Twitch and the current rebased version has that feature.

**Comment by MrSniFo** [comment]
Currently, it seems to be around 20% transparent, but it would be helpful to have a setting that allows adjusting the level of transparency for the background chat.
