### ISSUE TITLE
Emote does not working in livestream or in vod

### ISSUE THREAD

**Issue by ecan18** [bttv-android/bttv#633]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

The emote does not working in livestream or in vod. For me to see the emote, i need to open and close the app several times. 

### bttv-android version

v0.40.1 beta

### android version

13

### device

Samsung s21 ultra

**Comment by Maj-ew** [comment]
I confirm that as an issue but don't know for how long it has been, I even updated to newest version, still won't work

**Comment by icynstant** [comment]
Got this problem since week ago, maybe it has something to do with new Twitch updates or/and with Android 13.

**Comment by zakary2841** [comment]
Also, I have this issue. If I had to guess I reckon it has to do with the V2 API being sunset on November 1st 
![image](https://github.com/bttv-android/bttv/assets/26402356/f7d2224f-cc69-4f7a-89c1-ba2c7b4ce74d)

Hopefully, this helps to speed up the diagnostic process 😊

**Comment by zakary2841** [comment]
Just looked into this more. That is definitely the issue. 
https://github.com/bttv-android/bttv/blob/c0d227c610f5bc08f6287a69ffba0c8f6788a57a/mod/app/src/main/java/bttv/Network.java#L26


It will need replacing with the V3 API so I don't think it will be a quick fix. Especially if you are using the old username query as that has been removed.

**Comment by FoseFx** [comment]
Thank you everyone, especially @zakary2841 for identifying the root cause. Fix is rolling out now.
