### ISSUE TITLE
7TV emotes not appearing in high viewer/chatter streams

### ISSUE THREAD

**Issue by NickIs211** [bttv-android/bttv#639]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

![Screenshot_20231103_030946_BTTV](https://github.com/bttv-android/bttv/assets/7443232/3e889d9e-0370-4140-a204-edd7944ac812)
![Screenshot_20231103_031008_BTTV](https://github.com/bttv-android/bttv/assets/7443232/eca64317-84b8-47e5-8b46-0b9b47e780a2)

You can see in the first chat that xdd is not working, but in the next chat xdd is. The difference between the two is that the first stream has 50k+ viewers, while the second stream has 10k and is in slow mode. 

### bttv-android version

v0.40.2-beta

### android version

13

### device

Samsung Galaxy s22

**Comment by FoseFx** [comment]
There is a good chance your issues was fixed by today's release. Please reopen if that's not the case and provide some more information, like the channel which had missing emotes.
