### ISSUE TITLE
7tv emote that change name from 7tv global does not show

### ISSUE THREAD

**Issue by ecan18** [bttv-android/bttv#640]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

The 7tv emote that change name from 7tv site in stream does not appear. Thanks for the work.

### bttv-android version

v0.40.3 beta

### android version

13

### device

Samsung S21 ultra

**Comment by FoseFx** [comment]
I'm having issues understanding the bug. Can you quickly summarize the problem? What needs to happen for it to occur?

**Comment by ecan18** [comment]
Im sorry the issue fix. I think i need to to download the app again because in my other phone the app work perfectly

**Comment by jraug44** [comment]
I have an S21 Ultra too and I can confirm I have the exact same issue. Any emotes that are renamed will only replace the original name and the changed name will not show the emotes. Because of that it will often show the wrong emote or no emote at all. This was not an issue prior to the 7TV fix update; it worked just fine before. This seems like a device-specific issue; please fix this ASAP.

**Comment by FoseFx** [comment]
I'm still not sure what is happening here.  Can you give me a description on how to reproduce this?

**Comment by jraug44** [comment]
There's isn't really anything you need to do to reproduce this, just go to any channel that emotes renamed and some of them won't show correctly.

**Comment by ecan18** [comment]
This is the example that i can show: 
![photo_2023-11-06_16-10-43](https://github.com/bttv-android/bttv/assets/149601367/dcaf2e98-fa69-4f7b-8337-d46fc075c701)
this is not the correct emote name in that channel. and this is the correct emote name that from web .
![Screenshot 2023-11-06 160822](https://github.com/bttv-android/bttv/assets/149601367/d389ad3c-9409-46b5-b22e-8875645aff3f)
I think because some emote from channel have different name for 7tv emote than in the  7tv database cause it. Thank for the work.

**Comment by jraug44** [comment]
That's not an example because 7TV emotes don't show up in the box when you type a colon.
