### ISSUE TITLE
Non-global emotes don't show up in the suggestions

### ISSUE THREAD

**Issue by jraug44** [bttv-android/bttv#644]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [ ] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

If I type a : in the chat box non-global emotes don't show up in the list, then if I exit and re-enter the same channel it's suddenly working fine.

### bttv-android version

v.0.40.4-beta

### android version

13

### device

Samsung S21 Ultra

**Comment by FoseFx** [comment]
Can't reproduce, works fine for me

**Comment by jraug44** [comment]
![Screenshot_20231108_121705_BTTV](https://github.com/bttv-android/bttv/assets/149630943/468e47af-e8a7-419b-8167-451bf9c24a2c)
![Screenshot_20231108_121717_BTTV](https://github.com/bttv-android/bttv/assets/149630943/555c8c24-19b4-4f6a-89f6-87ab9643c85b)

**Comment by jraug44** [comment]
You don't have to load a stream at all, just going to a channel's chat works the same way.

**Comment by FoseFx** [comment]
Closed for can't repo :/
