### ISSUE TITLE
Clicking on an emote shows wrong name

### ISSUE THREAD

**Issue by jraug44** [bttv-android/bttv#647]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [ ] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

I clicked on an emote that had been renamed, it now showed the original name instead of the new name; typing a : in chat still showed the correct names

### bttv-android version

v.0.40.4-beta

### android version

13

### device

Samsung S21 Ultra

**Comment by jraug44** [comment]
I restart the app and it was normal again, I don't know what happened

**Comment by FoseFx** [comment]
We download the global sets of emotes for each provider once at start, and for each channel the first time you join the chat. Unlike 7TV, which keeps a websocket open to listen to changes, we do not, to reduce battery usage and for privacy concerns.

Read more here: https://github.com/bttv-android/bttv/issues/415
