### ISSUE TITLE
The chat covers the stream

### ISSUE THREAD

**Issue by Cingolani23** [bttv-android/bttv#651]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

When I put the chat with the stream in full screen, the chat covers what I am seeing on the screen, previously this problem did not happen since the stream was smaller and the chat and stream were visible.
As you can see in the screenshot, the strramer is playing GTA and the chat covers his health bar, chase level and almost half of the stream 
![Screenshot_20240110-230311](https://github.com/bttv-android/bttv/assets/156269373/5f4a77fb-c816-4813-8374-5b52e85dd6f3)

### bttv-android version

0.40.4-beta

### android version

Android 12

### device

Motorola Moto G51 5G

**Comment by FoseFx** [comment]
https://github.com/bttv-android/bttv/issues/243#issuecomment-910809756
