### ISSUE TITLE
Make the message that mentions the user connected in evidence

### ISSUE THREAD

**Issue by WassimeEY** [bttv-android/bttv#653]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Let's say my username is "jhon", if a message mentions me: "@jhon" 
actually the username become bold, but we can easily miss the message since we're not constanly looking at the chat.

**Describe the solution you'd like**

Why not make the background color yellow (or another color) so we can easily see when someone mentions us (for example: in desktop twitch the message is red).

**Comment by FoseFx** [comment]
You can add your name to the highlighted messages list like this: `<jhon>`. Then it will be highlighted like any other word in chat using this bttv feature.

(Your Profile -> Account Settings -> BTTV -> Set Highlight Keywords)
