### ISSUE TITLE
Emote Search

### ISSUE THREAD

**Issue by Clsmith2** [bttv-android/bttv#655]
From what I can tell there is no feature to allow for searching emotes. 

It's tedious scrolling through all the emotes to find the one you are looking for (if you don't remember what it's called or it's spelling) what I would recommend is something like the search that exists on the PC version, where you are given an option to search, filtering out emotes that don't match.

**Comment by FoseFx** [comment]
See https://github.com/bttv-android/bttv/issues/454#issuecomment-1107645392

**Comment by Clsmith2** [comment]
Thank you!
