### ISSUE TITLE
Update to the latest version that added stories and featured clips

### ISSUE THREAD

**Issue by jraug44** [bttv-android/bttv#660]
The stock Twitch app has new features that BTTV lacks because it hasn't been updated in a while, it would be nice to have those in BTTV

**Comment by alienware377** [comment]
Could anyone update this app to the current version of twitch with its new stuff supported and classic bttv-android bugs fixed? I'm willing to pay development time costs 😭😭😭 even just new stuff supported without bugs fixed is enough! Plz send me a PayPal money request with your required amount to lgs @ boun . cr (without spaces) on PayPal with stuff about what you'd fix on this app in the PayPal description (so I'll see the notification) and comment here to let me know who u are plzzz!! I've been waiting for an update on this for ages aaaa

**Comment by FoseFx** [comment]
Now tracked in #668
