### ISSUE TITLE
Hype train gets stuck

### ISSUE THREAD

**Issue by jraug44** [bttv-android/bttv#661]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

This has happened a lot where if there's a hype train, sometimes it never starts on my screen (it stays on the "Hype Train Is Near" notification) or if I join a stream in the middle of the hype train the meter never increases and the time counts down to 0:01 and gets stuck at 0:01. Also when this happens the notifications in chat for subscribing, gifted subs, and redeems don't show up either. This also is probably related to raids not working sometimes. I have to restart the app to fix it.

### bttv-android version

v 0.40.4-beta

### android version

13

### device

Samsung Galaxy S21 Ultra

**Comment by FoseFx** [comment]
Probably to be fixed by #668

**Comment by jraug44** [comment]
> Probably to be fixed by #668

It still does that

**Comment by FoseFx** [comment]
#668 is not done yet

**Comment by jraug44** [comment]
> [#668](https://github.com/bttv-android/bttv/issues/668) is not done yet

After the new update, the issue is still present. What happens is during a hype train, it stops refreshing so the timer goes down to 0:01 and stays there and it gets stuck on that level, even though the hype train is still going, requiring you to refresh to fix it. It also happens multiple times in a single hype train where I refresh and then it happens again.
