### ISSUE TITLE
Twitch warnings are not supported

### ISSUE THREAD

**Issue by MaybeAshleyIdk** [bttv-android/bttv#665]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

Recently (May 28, 2024) Twitch rolled out a new feature "warnings". ([official article](<https://help.twitch.tv/s/article/how-to-manage-harassment-in-chat#SendChatWarning>))

In the official app (version 19.8.0), the user correctly gets the warning bottom sheet where they have the click the Acknowledge button to be able to chat again.
![Screenshot of the official Twitch app with the warning bottom sheet visible](https://github.com/bttv-android/bttv/assets/142437333/cab12052-b839-4960-8706-3060d6e6d9ef)

In bttv-android, the user doesn't get the bottom sheet at all, resulting in the user being effectively shadow banned, as any messages the user sends aren't actually visible to any other user.

### bttv-android version

0.40.4-beta

### android version

Android 12

### device

Nokia 8.3 5G

**Comment by FoseFx** [comment]
Duplicate #668
