### ISSUE TITLE
chat split not working 

### ISSUE THREAD

**Issue by Komrade-Yanouchka** [bttv-android/bttv#673]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

![SmartSelect_20240824_012244_BTTV](https://github.com/user-attachments/assets/fb569a9b-fd7a-4678-a851-ee787956543a)
![SmartSelect_20240824_012808_BTTV](https://github.com/user-attachments/assets/60817997-2291-4b55-adc2-b9f9e78724ec)

### bttv-android version

0.41.0 beta

### android version

13

### device

galaxy tab s7+

**Comment by Zerwin** [comment]
This is something that probably broke during one of the rebases. I would ignore it for now until we are more up to date on the rebase versions. That way we only have to fix it once instead of it maybe breaking every few updates.

**Comment by Zerwin** [comment]
I noticed that it does work in VOD's, but not live streams

**Comment by SlimerSlumber** [comment]
Still facing this issue. Split chat, deleted messages, developer options do not work.
