### ISSUE TITLE
Announcements from Stream Elements don't show in live streams, only VODS

### ISSUE THREAD

**Issue by jraug44** [bttv-android/bttv#676]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [ ] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

There's a bug where certain messages from Stream Elements that have the "Announcement" header on desktop don't ever show up in live streams but when you watch the VOD they somehow do actually show up in chat.

### bttv-android version

v0.41.0-beta

### android version

13

### device

Samsung Galaxy S21 Ultra

**Comment by jraug44** [comment]
> Could you provide a picture or video of how this looks ? I'm not sure I correctly understand what you mean with Announcement header

There's certain messages in chat that on desktop will have a header that says "Announcement" above them. I'm talking about those particular messages.

**Comment by Zerwin** [comment]
Something like [this](https://d2opxh93rbxzdn.cloudfront.net/optimized/3X/7/6/767564b5bb2a833e5af52600ffdd849a1bd632ad_2_690x383.jpeg) ?

**Comment by jraug44** [comment]
> Something like [this](https://d2opxh93rbxzdn.cloudfront.net/optimized/3X/7/6/767564b5bb2a833e5af52600ffdd849a1bd632ad_2_690x383.jpeg) ?

YEP

**Comment by jraug44** [comment]
> > Something like [this](https://d2opxh93rbxzdn.cloudfront.net/optimized/3X/7/6/767564b5bb2a833e5af52600ffdd849a1bd632ad_2_690x383.jpeg) ?
> 
> YEP

![Screenshot_20240826_230028_BTTV](https://github.com/user-attachments/assets/3615f0fa-242c-4609-abe9-722a12811dd6)

This is an example

**Comment by AFranzo** [comment]
Pretty sure it's a native bug. Replicated in 20.9.0
### Browser
![webview](https://github.com/user-attachments/assets/51a88b60-7a57-4490-9788-d53bc98e2b94)
### Native Twitch App 
<img src="https://github.com/user-attachments/assets/e121989a-d3df-41fd-93ac-a8e20dd18837" width="500" />

**Comment by Zerwin** [comment]
Seeing how it's a native bug AND also still in the most current version, I doubt there is much we can do. @FoseFx What's your take ?

**Comment by FoseFx** [comment]
@AFranzo has confirmed this as a base bug, so this won't be fixed by us. Try https://twitch.uservoice.com/ to tell twitch about it (in case no-one else has yet).

Thank you everyone for discussing this!

**Comment by jraug44** [comment]
> @AFranzo has confirmed this as a base bug, so this won't be fixed by us. Try https://twitch.uservoice.com/ to tell twitch about it (in case no-one else has yet).
> 
> Thank you everyone for discussing this!

If there was a fix, that would require updating to the latest version with the new UI, unless there's way to keep the old UI somehow with the new fixes?

**Comment by Zerwin** [comment]
Probably. There might be a slim chances of backporting such a fix, but that still requires Twitch first to fix it at all, and the backport to be technically doable. Also it probably wouldn't happen before we rebased the app on some 20.X version.

**Comment by jraug44** [comment]
> Probably. There might be a slim chances of backporting such a fix, but that still requires Twitch first to fix it at all, and the backport to be technically doable. Also it probably wouldn't happen before we rebased the app on some 20.X version.

What would be the point of rebasing since the new UI doesn't have a followed and recommended page?

**Comment by jraug44** [comment]
> @AFranzo has confirmed this as a base bug, so this won't be fixed by us. Try https://twitch.uservoice.com/ to tell twitch about it (in case no-one else has yet).
> 
> Thank you everyone for discussing this!

I checked on desktop and it looks like announcements in VODS just show up as normal messages, which explains why they show up on mobile in the VODS, so it looks mobile twitch just has no support for that kind of message yet.
