### ISSUE TITLE
About copy and reply. Hype train and leader board. Playback speed. 

### ISSUE THREAD

**Issue by Vagacy** [bttv-android/bttv#677]
Problem 1: When new messages appear the holding action often get canceled since holding time for copying message and mention take too long to register. 
Solution: Reduce the holding time or Remove holding action and copy the message directly when tab.

Problem 2: Hype train and Leader board eating  chat space. The problem is severed when using the app in split screen, the chat box only show 2 messages.
Solution: Add hide option in setting. 

There's no playback speed for vod, could you please add this function too.

**Comment by FoseFx** [comment]
These are FRs to the twitch app itself, not bttv-android. Try https://twitch.uservoice.com/
