### ISSUE TITLE
Chat Resize! 

### ISSUE THREAD

**Issue by TomatoTurtlez** [bttv-android/bttv#693]
Would it be possible to change the font size and chat size for the video-chat side by side playback? Currently, chat is too big for my preference and occupies too much of the screen space. If I can resize the chat to make it smaller, it should give more screen space for the video to be bigger in size. 

I used Xtra on android previously and they had a setting for resizing chat :D

**Comment by FoseFx** [comment]
bttv-android is not a general-purpose mod and I think this is not in scope of the project.
