### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by AnotherDempsey** [bttv-android/bttv#696]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

Opening the app prompts an unskippable "App update required. Please install the latest version of the Twitch app from the App Store."

**Comment by Triset908** [comment]
Why was this closed as completed when it's still broken?

**Comment by AnotherDempsey** [comment]
I didn't realize there was a 0.41 update. That version still works. Unless
there's a reason to try and fix the 0.40.4 version, I don't see why it'd
need to be fixed?
