### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Koahollow** [bttv-android/bttv#697]
### Existing Issues

- [ ] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [ ] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

You need to update the app...
The app said i need to update in playstore
Sorry for my English

**Comment by spfrgo** [comment]
same for me

**Comment by Snowdac** [comment]
A temporary solution until they can work around twitch is to delete everything related to this apk and reinstall. It's inconvenient but it does work

**Comment by FoseFx** [comment]
Duplicate of #698 I guess? The title field is not optional.
