### ISSUE TITLE
Update is Required

### ISSUE THREAD

**Issue by owwouwu** [bttv-android/bttv#698]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

we can't access the app anymore, it's asking us to update the app from app store or watch streams from the browser 

### bttv-android version

0.41.0-beta

**Comment by galaxy-destroyer-raper** [comment]
Yeah i got the same problem, i was watching my favorite streamer and i had to close the app for a split second, but when i opened it back to enjoy it said that i need to update twitch via AppStore, i dont even have it i got an android phone, so yeah hope this bug get fixed soon

**Comment by owwouwu** [comment]
> Yeah i got the same problem, i was watching my favorite streamer and i had to close the app for a split second, but when i opened it back to enjoy it said that i need to update twitch via AppStore, i dont even have it i got an android phone, so yeah hope this bug get fixed soon

hopefully we get a fix, because the normal app is just terrible

**Comment by galaxy-destroyer-raper** [comment]
> > Yeah i got the same problem, i was watching my favorite streamer and i had to close the app for a split second, but when i opened it back to enjoy it said that i need to update twitch via AppStore, i dont even have it i got an android phone, so yeah hope this bug get fixed soon
> 
> hopefully we get a fix, because the normal app is just terrible

yeah the original twitch app is just eww, the multimillionare company cant make a user friendly app, what a shame

**Comment by Triset908** [comment]
Yeah they gotta fix this, I can't chat

**Comment by owwouwu** [comment]
> > > Yeah i got the same problem, i was watching my favorite streamer and i had to close the app for a split second, but when i opened it back to enjoy it said that i need to update twitch via AppStore, i dont even have it i got an android phone, so yeah hope this bug get fixed soon
> > 
> > hopefully we get a fix, because the normal app is just terrible
> 
> yeah the original twitch app is just eww, the multimillionare company cant make a user friendly app, what a shame

it's seems that the author @FoseFx hasn't been working on the app for quite a while, unfortunately we might not able to use this app ever again

**Comment by Triset908** [comment]
> > > > Yeah i got the same problem, i was watching my favorite streamer and i had to close the app for a split second, but when i opened it back to enjoy it said that i need to update twitch via AppStore, i dont even have it i got an android phone, so yeah hope this bug get fixed soon
> > > 
> > > 
> > > hopefully we get a fix, because the normal app is just terrible
> > 
> > 
> > yeah the original twitch app is just eww, the multimillionare company cant make a user friendly app, what a shame
> 
> it's seems that the author @FoseFx hasn't been working on the app for quite a while, unfortunately we might not able to use this app ever again

That sucks

**Comment by owwouwu** [comment]
> > > > > Yeah i got the same problem, i was watching my favorite streamer and i had to close the app for a split second, but when i opened it back to enjoy it said that i need to update twitch via AppStore, i dont even have it i got an android phone, so yeah hope this bug get fixed soon
> > > > 
> > > > 
> > > > hopefully we get a fix, because the normal app is just terrible
> > > 
> > > 
> > > yeah the original twitch app is just eww, the multimillionare company cant make a user friendly app, what a shame
> > 
> > it's seems that the author @FoseFx hasn't been working on the app for quite a while, unfortunately we might not able to use this app ever again
> 
> That sucks 

there's an app on play store called "dankchat" you will be able to see all the emotes and watch the streams as well, it's not as good but will do the work for now

**Comment by Triset908** [comment]
Uninstall is and reinstall, it worked for me

**Comment by Triset908** [comment]
Ok delete the app, delete any files of BTTV a and re-download it, it works again for me

**Comment by Snowdac** [comment]
> Ok delete the app, delete any files of BTTV a and re-download it, it works again for me

Can confirm this works but as the comment above me says a more permanent fix may take a bit

**Comment by jrsy85** [comment]
> Ok delete the app, delete any files of BTTV a and re-download it, it works again for me

Uninstall/reinstall worked here.

**Comment by owwouwu** [comment]
> I just did a quick check, the 41.0 Beta which is based on 16.9.1 Twitch app shows the forced update notice. The normal Twitch APK at that version also shows the update notice. The 16.9.0 version doesn't. My guess is Twitch saw that there were still ppl using that app version (probably cause we send the same string as the normal Twitch APK) and decided to force ppl to update.
> 
> The easy solution would be to release an update of the BTTV app that is based on a newer version. Work for that already got up to 19.0.1 before Fose and me kinda lost interest again. We haven't tested that version too indepth however, so there might be a few more bugs in there (and maybe some others are fixed, who knows).
> 
> I pinged Fose in the Discord, that's usually a safer way to get his attention, and will talk to him about releasing the new version. I can't promise a specific date or anything like that though.

thank you zerwin

**Comment by DerEichler** [comment]
Thanks for all the work guys. Honestly I could do without the custom emotes for now, as long as I don't have to use the god awful native twitch app. So I for one would vote to release the current branch (the one based on the v19.0.1) and take your time to maybe update to the current branch later on (if I understood your update correctly with 19.0.1 everything except the custom emotes works and it's just the full rebase to an even newer version that's not working with the apktool problem)

Again, thanks for the work and the updates.

**Comment by bj61251** [comment]
> Thanks for all the work guys. Honestly I could do without the custom emotes for now, as long as I don't have to use the god awful native twitch app. So I for one would vote to release the current branch (the one based on the v19.0.1) and take your time to maybe update to the current branch later on (if I understood your update correctly, with 19.0.1 everything except the custom emotes works and it's just the full rebase to an even newer version that's not working with the apktool problem)
> 
> Again, thanks for the work and the updates.

This is how I feel as well. I use the app simply as a way to find who is streaming and then cast it to my TV, so custom emotes are not important (I don't chat). The native app became incredibly cumbersome in this regard with the new redesign. I don't even want the stupid stories and featured clips on the home screen, either, which is why I want to continue using the oldest version possible (if you can make this a customizable part of the UI, that would be amazing). I just want a simple, clean interface to view who is live, and then cast it 😑

**Comment by mrbobbybooo** [comment]
The emote picker isn't showing the 7TV emotes

**Comment by FoseFx** [comment]
A fixed version is now available.

**Comment by FoseFx** [comment]
> I use the app simply as a way to find who is streaming and then cast it to my TV, so custom emotes are not important (I don't chat).

You might be better off by manually installing an old release of the Twitch App then, as it is very much intended for this mod to be up-to date with the upstream releases. It just isn't right now due to reasons.

**Comment by owwouwu** [comment]
> A fixed version is now available.
> 
> As the auto-updater is not triggered on start-up, you have to download it manually from the release page.
you are a legend, thank you 🙏

**Comment by owwouwu** [comment]
thank you @FoseFx you are a legend
