### ISSUE TITLE
Highlighted words functioning as blacklisted words

### ISSUE THREAD

**Issue by ChristineBean11** [bttv-android/bttv#700]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

I have set two terms as highlighted in the app, but as of the update, it seems like instead of highlighting those terms it is blocking them from appearing. I know this because I don't see them in the chat log, but they appear on stream (a particular streamer has chat shown on screen and I can see this messages there.)

### bttv-android version

v0.43.0-brta

### android version

15

### device

Google Pixel 9 Pro

### Anything else?

![Screenshot_20241210-151555~2](https://github.com/user-attachments/assets/e00ae80e-8907-4745-8fd7-d6df242e6137)
![Screenshot_20241210-151916](https://github.com/user-attachments/assets/b466d219-d825-47a5-8e68-c588e43b7a97)
![Screenshot_20241210-151920](https://github.com/user-attachments/assets/f7880013-9b06-44ad-a8a8-ea4775c908ca)

**Comment by FoseFx** [comment]
@all-contributors add @ChristineBean11 for bug
