### ISSUE TITLE
2x speed audio lag

### ISSUE THREAD

**Issue by ian15243** [bttv-android/bttv#705]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

Audio on 2x speed seems to buffer where the video plays but the audio freezes as if the audio is playing faster than the video

### bttv-android version

v0.43.0-beta

### android version

14

### device

Rog phone 8 pro

**Comment by FoseFx** [comment]
Sounds like the same issue as #691? Either way, as we don't mess with the video / audio processing, there is little to be done here.
