### ISSUE TITLE
bug: bttv settings not applied/saved

### ISSUE THREAD

**Issue by mangkoran** [bttv-android/bttv#708]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [X] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

Bttv settings is not applied/saved e.g. show deleted message, split chat, etc.

### bttv-android version

v0.43.0-beta

### android version

14

### device

Peridot

**Comment by Zerwin** [comment]
Already created a PR with a fix for this https://github.com/bttv-android/bttv/pull/707 just waiting for @FoseFx to take a look at it

**Comment by FoseFx** [comment]
Fixed via #707

**Comment by Zerwin** [comment]
Split chat is/was broken too. I recently also pushed out a PR for that https://github.com/bttv-android/bttv/pull/688

**Comment by mangkoran** [comment]
Ah so split chat is actually broken 😅

If that's the case then I can confirm other settings is now persisted and working as intended. Thank you!
