### ISSUE TITLE
Adblock would be cool

### ISSUE THREAD

**Issue by CKraft11** [bttv-android/bttv#87]

**Comment by FoseFx** [comment]
This is a tough one. I really don't want to start a war with twitch. If they see revenue going down in any significant way they DMCA the repo or start making my life harder by implementing obfuscation measures and alike.

I personally use a [pihole](https://pi-hole.net/) and it works great.

**Comment by SekaiiArts** [comment]
> This is a tough one. I really don't want to start a war with twitch. If they see revenue going down in any significant way they DMCA the repo or start making my life harder by implementing obfuscation measures and alike.
> 
> I personally use a [pihole](https://pi-hole.net/) and it works great.

Note to remember; there are people who watch twitch on their pc with adblock. Perhaps using adblock may not affect such statistics if pc adblock users are using app adblock, however I don't know, just something to point out

**Comment by einekratzekatze** [comment]
Please reopen this Issue.

If you really believe Twitch would come after you read this mail send to the Twitch Adblock Chrome exension. 
![IMG_0941.png](https://github.com/bttv-android/bttv/assets/48450457/f6907a9f-bf88-4d93-a2b8-c7e522ec38fa)
![IMG_20230818_022647.jpg](https://github.com/bttv-android/bttv/assets/48450457/e064c1d8-eb24-44d2-b11a-eb7ef533ae6e)


There are already adblock patches by revanced, so it should be easy to implement.
