### ISSUE TITLE
Sleep timer

### ISSUE THREAD

**Issue by Epicnicity322** [bttv-android/bttv#88]
A timer that you can set to automatically close the app and lock your phone screen, so you can set it before sleeping

**Comment by FoseFx** [comment]
Is this what you had in mind?
https://github.com/bttv-android/bttv/suites/2939511684/artifacts/66050114 (link is only valid for a day)

**Comment by Epicnicity322** [comment]
Sorry, I didn't get notified by your reply. Do you still have the artifact? If not that's okay, there are apps for this, I just thought it would be cool for it to be built-in in this app, like Xtra for Twitch had.

**Comment by FoseFx** [comment]
I just released [0.7.0-beta](https://github.com/bttv-android/bttv/releases/tag/v0.7.0-beta) and this feature is part of it.

**Comment by Epicnicity322** [comment]
Thank you very much! I love your app

**Comment by FoseFx** [comment]
@all-contributors please add @Epicnicity322 for ideas
